# Site settings
title: Andy Orahoske | Web Developer Cincinnati, OH
email: orahoske.2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the personal site for Andrew Orahoske. I am a front end
  web developer in Cincinnati, OH.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  AO16

# Build settings
markdown: kramdown
